import {useEffect} from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Thanks.module.css'
export default function Thanks() {
    useEffect(() => {
        window.localStorage.clear()
    }, [])
  return (
    <div className={styles.container}>
      <Head>
        <title>Thank You - NFt-Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <header className={styles.header}>
            <h1>THANK YOU!</h1>
        </header>

        <div className={styles.description}>
            <p class="main-content__body" data-lead-id="main-content-body">Thank you very much for ordering from us. BUT IF WANT TO BUT REAL NFTs YOU CAN GO ON (OpenSea, Axie Marketplace, CryptoPunks ETC)</p>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="#"
          target="_blank"
          rel="noopener noreferrer"
        >
          It's a project website NFT
        </a>
      </footer>
    </div>
  )
}
